apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::566582774977:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::566582774977:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-ZTTSDS1W0PTG
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-24T00:14:27Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1403"
  uid: a8881d42-8493-473e-88fb-988cda7b1375
